version: '2'
services:
  nym-mixnode:
    image: nym-mixnode
    container_name: nym-mixnode
    restart: unless-stopped
    mem_limit: 256mb
    ports:
      - 1789:1789
    build:
      context: ./
    volumes:
      - ./config.toml:/root/.nym/mixnodes/mixer/config/config.toml
    command: "nym-mixnode run --id=mixer"
